# Numpy - 그 밖의 형태

## #01. 준비과정

### [1] 패키지 참조

In [223]:
import numpy as np

## #02. 2차원 배열

### [1] 2차원 배열의 생성

In [224]:
# 철수의 학년-과목별 점수
grade = np.array([
            [98, 72, 80, 64],
            [88, 90, 80, 72],
            [92, 88, 82, 76]
        ])
grade

array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82, 76]])

### [2] 2차원 배열의 크기

#### (1) 차원 크기

In [225]:
grade.ndim

2

#### (2) 각 차원별 원소수

In [226]:
grade.shape

(3, 4)

#### (3) 원소의 데이터 타입

In [227]:
grade.dtype

dtype('int32')

### [3] 2차원 배열의 기초 통계량

#### (1) 각 열끼리 더함 (세로로 덧셈)

결과 타입은 numpy의 1차 배열

In [228]:
s1 = np.sum(grade, axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([278, 250, 242, 212])

#### (2) 각 행끼리 더함 (가로로 덧셈)

In [229]:
s2 = np.sum(grade, axis=1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([314, 330, 338])

### [4] 조건검색

#### (1) boolean 타입으로 인덱싱

조건에 맞는 값들을 1차원으로 반환한다.

In [230]:
bool_array = np.array([
            [True, False, True, False],
            [True, True, True, False],
            [True, True, True, False]
        ])

# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

#### (2) 비교식에 의한 검색

80점 이상인지 판별하여 조건에 맞는 데이터만 추려냄

In [231]:
result2 = grade[grade >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

#### (3) `AND` 검색

In [232]:
result3 = grade[np.logical_and(grade >= 80, grade <= 90)]
result3

array([80, 88, 90, 80, 88, 82])

#### (4) `OR` 검색

In [233]:
result4 = grade[np.logical_or(grade < 80, grade > 90)]
result4

array([98, 72, 64, 72, 92, 76])

## #03. 정형화된 배열 생성

### [1] 모든 원소가 `0`인 배열

In [234]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### [2] 모든 원소가 `1`인 배열

In [235]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### [3] 모든 원소가 특정값인 배열

In [236]:
np.full([3, 4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### [4] 단위행렬

대각선으로 `1`이고 나머지 원소는 모두 `0`인 배열

In [237]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## #04. 랜덤 배열

### [1] `0`부터 `1`의 범위에서 균등하게 추출하여 N차원 배열 생성

#### 10개의 값을 갖는 1차원 배열

In [238]:
np.random.rand(10)

array([0.37025075, 0.56119619, 0.50308317, 0.01376845, 0.77282662,
       0.88264119, 0.36488598, 0.61539618, 0.07538124, 0.36882401])

#### 4행 3열인 2차원 배열

In [239]:
np.random.rand(4, 3)

array([[0.9331401 , 0.65137814, 0.39720258],
       [0.78873014, 0.31683612, 0.56809865],
       [0.86912739, 0.43617342, 0.80214764],
       [0.14376682, 0.70426097, 0.70458131]])

### [2] 주어진 범위 안에서 정수값을 갖는 랜덤 배열

#### `0`부터 `9`사이의 랜덤값 10개의 원소를 갖는 1차원 배열

In [240]:
np.random.randint(0, 9, 10)

array([1, 5, 4, 0, 8, 8, 6, 8, 6, 3])

#### `0`부터 `9`사이의 랜덤값을 갖는 3행 4열의 2차 배열

In [241]:
np.random.randint(0, 9, (3, 4))

array([[1, 2, 5, 2],
       [5, 6, 7, 4],
       [3, 5, 6, 4]])

### [3] 표준 정규 분포를 따르는 랜덤 배열

#### 1차원 배열

In [242]:
np.random.randn(10)

array([-0.30914716, -2.03239595, -0.17446818, -0.64247527, -0.62502311,
        1.3258867 ,  0.5312549 ,  1.27528435, -0.68282564, -0.94818614])

#### 2차원 배열

In [243]:
np.random.randn(4, 3)

array([[ 0.7773618 ,  0.3251135 , -1.20348608],
       [ 1.20954346,  0.15762162, -0.29355482],
       [ 0.11155997,  0.59767854, -1.270093  ],
       [ 0.12094906, -0.19389815,  1.8041719 ]])

### [4] 정규분포를 직접 설정

#### 1차원 배열

평균은 `0`, 표준편차 `1`의 정규 분포에서 10개의 수를 추출

In [244]:
np.random.normal(0, 1, 10)

array([-0.23469376,  0.9399084 , -0.17152003, -0.15305462, -0.36309497,
       -0.06731792,  1.4447209 ,  0.32577085, -0.85573249, -0.69759516])

#### 2차원 배열

In [245]:
np.random.normal(0, 1, (4, 3))

array([[-0.27613406, -1.25875935,  0.47809372],
       [-0.85976366,  0.57198791, -0.17396519],
       [ 1.53490024,  0.87285598,  1.85683523],
       [ 0.02591389,  0.17198358, -0.19116304]])

### [5] 랜덤값 고정

랜덤이란 사전에 잘 섞여 있는 숫자 셋을 순차적으로 꺼내는 것을 의미

랜덤시드는 몇 번째 숫자셋인지를 의미하는 값

이 값을 고정하면 특정 숫자셋만 사용하라는 의미

In [246]:
np.random.seed(1234)
np.random.normal(0, 1, (4, 3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])