In [1]:
import numpy as np

### 넘파이 형태변환

#### 타입변환

- 배열 원소의 데이터 타입을 변환하는 방법 : astype() 메서드를 사용하는 방법과 asarray() 함수를 사용하는 방법

- astype() 메서드

In [4]:
arr1 = np.arange(10)
print("원본배열 :", arr1)
print("원본배열의 데이터 타입 :", arr1.dtype)

원본배열 : [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입 : int32


- 실수 타입으로 변환

In [7]:
arr2 = arr1.astype('float')

print("형변환 후의 배열 :", arr2)
print("변환된 배열의 데이터 타입 :", arr2.dtype)

형변환 후의 배열 : [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입 : float64


- 문자열 타입으로 변환

In [8]:
arr3 = arr1.astype('str')

print("형변환 후의 배열 :", arr3)
print("변환된 배열의 데이터 타입 :", arr3.dtype)

형변환 후의 배열 : ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입 : <U11


- asarray() 함수

In [12]:
arr1 = np.arange(10, 20)
print("원본배열 :", arr1)
print("원본배열의 데이터 타입 :", arr1.dtype)

원본배열 : [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입 : int32


- 실수 타입으로 변환
  - 변환할 원본 배열과 타입(dtype)을 파라미터로 설정

In [15]:
arr2 = np.asarray(arr1, dtype = 'float')
print("형변환 후의 배열 :", arr2)
print("변환된 배열의 데이터 타입 :", arr2.dtype)

형변환 후의 배열 : [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입 : float64


In [16]:
arr3 = np.asarray(arr1, dtype = 'str')
print("형변환 후의 배열 :", arr3)
print("변환된 배열의 데이터 타입 :", arr3.dtype)

형변환 후의 배열 : ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입 : <U11


#### 차원변환

- 1차원 배열을 다차원으로 변환하기

In [17]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- (4, 5) 2차원 배열로 변환
  - reshape(행, 열) 메서드를 사용
  - 행, 열로 재구성했을 경우 원소의 수가 나누어 떨어져야 한다 (남거나 모자라서는 안된다)
    - 맞는 값이 아니면 에러 발생

In [19]:
x = origin.reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 3차원 배열로 변환
  - 2행 5열이 2개

In [20]:
y = origin.reshape(2, 2, 5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

- 차원 축소
  - 원본 배열 구성

In [22]:
origin = np.array([[ 0,  1,  2,  3,  4],
                    [ 5,  6,  7,  8,  9],
                    [10, 11, 12, 13, 14],
                    [15, 16, 17, 18, 19]])

origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 1차원으로 축소

In [26]:
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- 1차원으로 변환할 경우 일일히 원소의 수를 카운트하기는 번거로우므로 'shape'를 구해서 활용한다.

In [29]:
rows, cols = origin.shape
rows, cols

(4, 5)

In [30]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

- -1의 의미
  - reshape를 활용하는 경우 입력 파라미터로 -1이 들어가는 경우가 있음
  - -1은 원래 배열의 길이와 남은 차원으로부터 추정이라는 뜻
    - 남은 n개

In [31]:
origin = np.array([[ 0,  1,  2,  3],
                    [ 4,  5,  6,  7],
                    [8, 9, 10, 11],])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 1열로 구성된 배열로 2차원 배열로 재배치

In [34]:
x = origin.reshape(-1, 1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

- 2열 구성

In [35]:
y = origin.reshape(-1, 2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

- 3열 구성

In [37]:
z = origin.reshape(-1, 3)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- 행의 수를 고정

In [38]:
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 열의 수에 관계 없이 2행을 갖는 2차원 배열로 재구성

In [39]:
x = origin.reshape(2, -1)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

- 3행 구성

In [41]:
y = origin.reshape(3, -1)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 4행 구성

In [42]:
z = origin.reshape(4, -1)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- reshape(-1)인 경우

In [43]:
origin = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10, 11]])
origin

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

- 1차원 배열로 변환

In [44]:
x = origin.reshape(-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 2차원 배열로 변환
  - 행의 수는 1개이며 열의 수는 -1을 지정

In [45]:
y = origin.reshape(1, -1)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [54]:
origin.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
origin.transpose()

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [55]:
origin.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])