In [1]:
import sys
import os
work_path = os.path.abspath(os.path.join(os.getcwd(), "../../.."))
sys.path.append(work_path)

from scipy.stats import chi2_contingency, chisquare
import numpy as np
import pandas as pd
from ljk_module.preprocessing import *

In [2]:
x = np.random.randint(1, 100, 100)
y = np.random.randint(1, 100, 100)

In [3]:
chi2_contingency(x, y)

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=0, expected_freq=array([88., 74., 21., 21., 42.,  2., 15., 91., 65., 34., 94., 77., 62.,
       49., 71., 89., 56., 67., 62., 41., 80., 48., 40., 51., 20., 19.,
       77., 75.,  8., 15., 48., 21., 26., 61., 60., 35., 64., 40., 37.,
       32., 18., 47., 25., 34., 61., 75., 67., 97., 52., 54., 15., 83.,
       48., 38., 56., 65., 14., 56., 10., 51., 48., 24., 16., 86., 97.,
       12., 72., 29., 34., 37., 31., 43., 53., 69., 99., 10., 62., 61.,
       65., 36., 72., 60.,  5., 45., 13., 21., 35., 69., 46., 17., 56.,
       71., 93.,  2., 40., 56.,  4.,  9., 10., 30.]))

In [4]:
chisquare(x, y/sum(y)*sum(x))

Power_divergenceResult(statistic=16572.50894925258, pvalue=0.0)

In [5]:
df = pd.read_excel("./data/diamonds.xlsx")

In [6]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [7]:
df2_1 = df.iloc[:int(len(df)/2), :]
df2_2 = df.iloc[int(len(df)/2):, :]

In [8]:
X1 = df2_1.copy()
X2 = df2_2.copy()
Y1 = X1.pop('price')
Y2 = X2.pop('price')

In [9]:
pp = LjkPreprocessor()

In [10]:
pp.set_strategy(outline = 'q', null = 'mean', scaler = 'm', encoder = 'o')

아래와 같이 처리합니다.
+-------------+-----------------+
| 범주        | 처리방법        |
|-------------+-----------------|
| 이상치 처리 | 경계값 대체     |
| 결측치 처리 | 평균값 대체     |
| 스케일러    | MinMax 스케일러 |
| 인코딩      | 원핫인코딩      |
+-------------+-----------------+


In [11]:
Z1 = pp.fit_transform(df = X1)

데이터프레임 크기 : (26970, 9)
데이터프레임에 결측치는 없습니다.
연속형 데이터 컬럼 : ['carat', 'depth', 'table', 'x', 'y', 'z'], 총 6개
명목형 데이터 컬럼 : ['cut', 'color', 'clarity'], 총 3개


In [12]:
Z1.head()

carat     depth     table    x    y    z  cut_Fair  cut_Good  cut_Ideal  \
0    0.0  0.453125  0.291667  0.0  0.0  0.0       0.0       0.0        1.0   
1    0.0  0.187500  0.791667  0.0  0.0  0.0       0.0       0.0        0.0   
2    0.0  0.000000  1.000000  0.0  0.0  0.0       0.0       1.0        0.0   
3    0.0  0.593750  0.541667  0.0  0.0  0.0       0.0       0.0        0.0   
4    0.0  0.734375  0.541667  0.0  0.0  0.0       0.0       1.0        0.0   

   cut_Premium  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0          0.0  ...      0.0      0.0         0.0         0.0          0.0   
1          1.0  ...      0.0      0.0         0.0         0.0          1.0   
2          0.0  ...      0.0      0.0         0.0         0.0          0.0   
3          1.0  ...      1.0      0.0         0.0         0.0          0.0   
4          0.0  ...      0.0      1.0         0.0         0.0          0.0   

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0          1.0          0.0          0.0           0.0           0.0  
1          0.0          0.0          0.0           0.0           0.0  
2          0.0          1.0          0.0           0.0           0.0  
3          0.0          0.0          1.0           0.0           0.0  
4          1.0          0.0          0.0           0.0           0.0  

[5 rows x 26 columns]

In [13]:
Z2 = pp.transform(df2 = X2)

데이터프레임 크기 : (26970, 9)
데이터프레임에 결측치는 없습니다.


In [14]:
Z2.head()

carat     depth     table         x         y         z  cut_Fair  \
26970  0.847973  0.531250  0.208333  0.784884  0.782738  0.783163       0.0   
26971  1.000000  0.109375  0.791667  1.000000  1.000000  1.000000       0.0   
26972  1.000000  0.500000  0.458333  0.991279  0.982143  1.000000       0.0   
26973  0.922297  0.000000  0.791667  0.886628  0.869048  0.772959       0.0   
26974  1.000000  0.593750  0.458333  1.000000  1.000000  1.000000       0.0   

       cut_Good  cut_Ideal  cut_Premium  ...  color_I  color_J  clarity_I1  \
26970       0.0        1.0          0.0  ...      0.0      0.0         0.0   
26971       1.0        0.0          0.0  ...      0.0      1.0         0.0   
26972       0.0        1.0          0.0  ...      0.0      0.0         0.0   
26973       0.0        0.0          0.0  ...      0.0      0.0         0.0   
26974       0.0        0.0          1.0  ...      0.0      1.0         0.0   

       clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
26970         0.0          0.0          0.0          1.0          0.0   
26971         0.0          0.0          0.0          1.0          0.0   
26972         0.0          0.0          0.0          0.0          1.0   
26973         0.0          0.0          0.0          0.0          1.0   
26974         0.0          0.0          0.0          0.0          1.0   

       clarity_VVS1  clarity_VVS2  
26970           0.0           0.0  
26971           0.0           0.0  
26972           0.0           0.0  
26973           0.0           0.0  
26974           0.0           0.0  

[5 rows x 26 columns]

- K-Fold

In [26]:
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score, cross_validate
from sklearn.linear_model import LinearRegression

In [27]:
df = pd.read_excel("./data/fish.xlsx")
df.head()

길이    높이    두께    무게
0   8.4  2.11  1.41   5.9
1  13.7  3.53  2.00  32.0
2  15.0  3.82  2.43  40.0
3  16.2  4.59  2.63  51.5
4  17.4  4.59  2.94  70.0

In [28]:
yname = '무게'
x = df.drop(yname, axis = 1)
y = df[yname]

In [116]:
kf = KFold(n_splits = 10)

In [92]:
k = 10
model = LinearRegression(n_jobs = -1)
scores = cross_val_score(model, x, y, cv = k, scoring = 'r2', n_jobs = -1)

In [93]:
scores

array([-5.80130229e+01, -2.31476956e+00, -4.52072266e+01, -4.47723355e+00,
       -5.35954360e+00, -1.75520025e+01,  6.25492054e-01,  5.30196516e-01,
       -5.03267727e-02, -1.75845285e+01])

In [42]:
scores.max()

0.6254920541938509

In [39]:
scores.argmax() + 1

8

In [43]:
model = LinearRegression(n_jobs = -1)

In [81]:
?cross_validate

Signature:
cross_validate(
    estimator,
    X,
    y=None,
    *,
    groups=None,
    scoring=None,
    cv=None,
    n_jobs=None,
    verbose=0,
    fit_params=None,
    pre_dispatch='2*n_jobs',
    return_train_score=False,
    return_estimator=False,
    error_score=nan,
)
Docstring:
Evaluate metric(s) by cross-validation and also record fit/score times.

Read more in the :ref:`User Guide <multimetric_cross_validation>`.

Parameters
----------
estimator : estimator object implementing 'fit'
    The object to use to fit the data.

X : array-like of shape (n_samples, n_features)
    The data to fit. Can be for example a list, or an array.

y : array-like of shape (n_samples,) or (n_samples, n_outputs), default=None
    The target variable to try to predict in the case of
    supervised learning.

groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :t

In [170]:
result = cross_validate(model, x, y, cv = 10, scoring = ['r2', 'neg_mean_absolute_error'], return_train_score = True, return_estimator = True, n_jobs = -1)

In [171]:
result_df = pd.DataFrame(result)

In [172]:
result_df

fit_time  score_time                    estimator    test_r2  train_r2  \
0  0.003079    0.000885  LinearRegression(n_jobs=-1) -58.013023  0.969328   
1  0.002960    0.001009  LinearRegression(n_jobs=-1)  -2.314770  0.937610   
2  0.002414    0.000546  LinearRegression(n_jobs=-1) -45.207227  0.939373   
3  0.002960    0.001009  LinearRegression(n_jobs=-1)  -4.477234  0.940413   
4  0.002960    0.001009  LinearRegression(n_jobs=-1)  -5.359544  0.943642   
5  0.002554    0.001001  LinearRegression(n_jobs=-1) -17.552003  0.948462   
6  0.001894    0.000999  LinearRegression(n_jobs=-1)   0.625492  0.945635   
7  0.001999    0.001170  LinearRegression(n_jobs=-1)   0.530197  0.938041   
8  0.001999    0.002178  LinearRegression(n_jobs=-1)  -0.050327  0.931972   
9  0.002170    0.001008  LinearRegression(n_jobs=-1) -17.584529  0.944070   

   test_neg_mean_absolute_error  train_neg_mean_absolute_error  
0                   -203.315347                     -47.524587  
1                    -23.760202                     -67.005153  
2                    -34.277430                     -67.671913  
3                    -39.691354                     -66.679700  
4                    -64.376062                     -65.022151  
5                    -85.960274                     -63.067058  
6                   -100.334143                     -61.460363  
7                    -47.105947                     -65.508727  
8                    -66.217669                     -61.742216  
9                   -194.999807                     -51.351213

In [80]:
maxindex = result_df['test_score'].argmax()
best_model = result_df.iloc[maxindex]['estimator']
best_model

LinearRegression(n_jobs=-1)

In [52]:
y_predict = cross_val_predict(model, x, y, cv = maxindex + 1, n_jobs = -1)
y_predict

array([-415.07853167, -226.51199473, -170.5319201 , -102.50092462,
        -68.04456227,   -9.39059305,   -7.16198571,   16.88762632,
         63.61423719,   41.92835141,  139.71780356,  139.54040268,
        147.04399414,  187.58426947,  161.29346999,  134.95737725,
        171.75681189,  155.22220036,  160.06735997,  161.06534327,
        227.92268556,  168.52744392,  116.5759082 ,  199.41972277,
        276.25603007,  221.46559183,  269.52394449,  219.52200383,
        265.68650727,  303.05013887,  447.64446312,  319.07001843,
        312.17502048,  343.23703929,  353.00323619,  372.34359822,
        388.28133524,  641.13625561,  688.40093468,  869.19466922,
        759.52498486,  729.72075358,  728.31303342,  709.7854361 ,
        814.30380312,  744.33044163,  920.9310011 ,  866.73418149,
        754.01238957,  813.11997327,  655.80233646,  749.79587392,
        752.08029315,  795.94389038,  883.27908607,  810.40730325])

In [114]:
lot = x.iloc[:45, :]

In [117]:
for i in kf.split(lot):
    print(i)

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44]), array([0, 1, 2, 3, 4]))
(array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44]), array([5, 6, 7, 8, 9]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44]), array([10, 11, 12, 13, 14]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44]), array([15, 16, 17, 18, 19]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       

In [108]:
?KFold

Init signature: KFold(n_splits=5, *, shuffle=False, random_state=None)
Docstring:     
K-Folds cross-validator

Provides train/test indices to split data in train/test sets. Split
dataset into k consecutive folds (without shuffling by default).

Each fold is then used once as a validation while the k - 1 remaining
folds form the training set.

Read more in the :ref:`User Guide <k_fold>`.

Parameters
----------
n_splits : int, default=5
    Number of folds. Must be at least 2.

    .. versionchanged:: 0.22
        ``n_splits`` default value changed from 3 to 5.

shuffle : bool, default=False
    Whether to shuffle the data before splitting into batches.
    Note that the samples within each split will not be shuffled.

random_state : int, RandomState instance or None, default=None
    When `shuffle` is True, `random_state` affects the ordering of the
    indices, which controls the randomness of each fold. Otherwise, this
    parameter has no effect.
    Pass an int for reproducible out

In [127]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from my_helper.util import *

In [125]:
df.head()

길이    높이    두께    무게
0   8.4  2.11  1.41   5.9
1  13.7  3.53  2.00  32.0
2  15.0  3.82  2.43  40.0
3  16.2  4.59  2.63  51.5
4  17.4  4.59  2.94  70.0

In [130]:
df2 = my_standard_scaler(df, '무게')
df2.head()

길이        높이        두께    무게
0 -2.180225 -2.016507 -1.896175   5.9
1 -1.587434 -1.518703 -1.560774  32.0
2 -1.442032 -1.417039 -1.316328  40.0
3 -1.307815 -1.147103 -1.202633  51.5
4 -1.173599 -1.147103 -1.026405  70.0

In [131]:
yname = '무게'
x = df2.copy()
y = x.pop(yname)
x.shape, y.shape

((56, 3), (56,))

In [135]:
model = LinearRegression(n_jobs = -1)
params = {}
fold = 10

grid_cv = GridSearchCV(model, param_grid = params, cv = fold)

grid_cv.fit(x, y)

GridSearchCV(cv=10, estimator=LinearRegression(n_jobs=-1), param_grid={})

In [136]:
grid_cv.best_params_

{}

In [137]:
grid_cv.best_estimator_

LinearRegression(n_jobs=-1)

In [138]:
from xgboost import XGBRegressor

In [142]:
xgb = XGBRegressor(random_state = 0)

In [140]:
params2 = {
    'max_depth' : [3, 5, 7, 9, 11, 13, 15],
    'max_leaves' : [0, 10, 100, 1000],
    'learning_rate' : [0.1, 0.01, 0.001, 0.0001]
}

In [143]:
gs = GridSearchCV(xgb, param_grid = params2, cv = kf)

In [146]:
gs.fit(x, y)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=0, ...),
             param_grid={'learning_rate': [0.1, 0.01, 0.001, 0.0001],
                         'max_depth': [3, 5, 7, 9, 11, 13, 15],
                         'max_leaves': [0, 10, 100, 1000]})

In [148]:
gs.best_params_

{'learning_rate': 0.1, 'max_depth': 3, 'max_leaves': 0}

In [150]:
xgb2 = gs.best_estimator_

In [154]:
import sklearn.model_selection

In [163]:
dir(sklearn.model_selection)

['BaseCrossValidator',
 'BaseShuffleSplit',
 'GridSearchCV',
 'GroupKFold',
 'GroupShuffleSplit',
 'KFold',
 'LearningCurveDisplay',
 'LeaveOneGroupOut',
 'LeaveOneOut',
 'LeavePGroupsOut',
 'LeavePOut',
 'ParameterGrid',
 'ParameterSampler',
 'PredefinedSplit',
 'RandomizedSearchCV',
 'RepeatedKFold',
 'RepeatedStratifiedKFold',
 'ShuffleSplit',
 'StratifiedGroupKFold',
 'StratifiedKFold',
 'StratifiedShuffleSplit',
 'TimeSeriesSplit',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_plot',
 '_search',
 '_split',
 '_validation',
 'check_cv',
 'cross_val_predict',
 'cross_val_score',
 'cross_validate',
 'learning_curve',
 'permutation_test_score',
 'train_test_split',
 'typing',
 'validation_curve']

In [164]:
from sklearn.model_selection import StratifiedKFold, ShuffleSplit

In [158]:
skf = StratifiedKFold(n_splits = 10)

In [166]:
ss = ShuffleSplit(n_splits = 10, test_size = 0.3)

In [165]:
?ShuffleSplit

Init signature:
ShuffleSplit(
    n_splits=10,
    *,
    test_size=None,
    train_size=None,
    random_state=None,
)
Docstring:     
Random permutation cross-validator

Yields indices to split data into training and test sets.

Note: contrary to other cross-validation strategies, random splits
do not guarantee that all folds will be different, although this is
still very likely for sizeable datasets.

Read more in the :ref:`User Guide <ShuffleSplit>`.

Parameters
----------
n_splits : int, default=10
    Number of re-shuffling & splitting iterations.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.1.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and rep